### ISSUE TITLE
PXmonja

### ISSUE THREAD

**Issue by tanyo13** [zr-tex8r/pythmeni#1]
PXmonjaについて気づいた点を報告します．書くべき場所が違っていたら申し訳ありません．
1. 配布サイトのページ http://zrbabbler.sp.land.to/pxmonja.html 内にある zip ファイルへのリンクのリンク先が PXmika のファイル (pxmika.zip) になっています．(http://zrbabbler.sp.land.to/package.html 内のリンクは正しいものです)
2. READMEファイル中に，dvipdfmx用のmapファイル pdfm-pxmonja.map を，$TEXMF/fonts/map/dvipdfm/pxmonja/ に置くように指示がありますが，.../dvipdfmx/... に置かないと動きませんでした．(バージョン等によって違いがあるのかとも思いましたが，よくわからないので，一応，報告します．)
3. \usepackage{pxmonja} の状態で `ABC\verb=DEF=GHI` と書くと，CとDの間に空白が入ってしまいます (pxmonjaがなければ入りません)．意図した動作でしょうか? pxmonja.sty の148行目 (\domonja の定義の2行目) の行末に % を置くとこの空白は消えますので，書き直して使っています．

**Comment by zr-tex8r** [comment]
なるほど、このリポジトリには、そういう使い方もあるんですね……;-)

それはともかく、PXmonjaのリポジトリを作りました。
そこで修正版（v0.2a）を公開しています。
- https://github.com/zr-tex8r/PXmonja

>    ../dvipdfmx/... に置かないと動きませんでした．(バージョン等によって違いがあるのかとも思いましたが，よくわからないので，一応，報告します．)

大昔は dvipdfm だったのでした。

>    意図した動作でしょうか?

単純にバグです `m__m`

ありがとうございました。
